[diag] use sock_set_rcvbuf() instead of kernel_setsockopt()
drivers/char/diag/diagfwd_socket.c
Sets SO_RCVBUF on the QRTR socket with sock_set_rcvbuf(sk, size). The
kernel_setsockopt() call is replaced because that helper no longer exists.

drivers/char/diag/diagfwd_socket.c:509:2: error: implicit declaration of function 'kernel_setsockopt'

Signed-off-by: Varakumar <varakumar7000@gmail.com>