[net] sync the TCP and socket-filter files with Sakura.MTX-23.2
net/ipv4/tcp.c
net/ipv4/icmp.c
net/core/filter.c
net/packet/af_packet.c
net/mptcp/protocol.c
include/linux/tcp.h
include/linux/filter.h
include/net/tcp.h
include/uapi/asm-generic/socket.h
Replaces these files with the versions from Sakura.MTX-23.2. Replaying the
sockopt/compat series left them in a state that does not build: tcp.c has
a broken do_tcp_setsockopt() region and lost set_thash_entries() and
__tcp_sock_set_quickack(), filter.c defines copy_bpf_fprog_from_user()
twice, and SO_PREFER_BUSY_POLL / SO_BUSY_POLL_BUDGET are missing from the
generic socket.h that mptcp/sockopt.c uses.

net/ipv4/tcp.c:3215:1: error: expected expression
net/ipv4/tcp.c:3973:27: error: use of undeclared identifier 'set_thash_entries'; did you mean 'thash_entries'?
net/core/filter.c:88:5: error: conflicting types for 'copy_bpf_fprog_from_user'
net/mptcp/sockopt.c:315:7: error: use of undeclared identifier 'SO_PREFER_BUSY_POLL'

Signed-off-by: Varakumar <varakumar7000@gmail.com>
Credits: Madara273 (https://github.com/Madara273/Sakura.MTX-OP9-Pro) - these files and the upstream patch series behind them