[staging] stealth: use file_operations, struct proc_ops doesn't exist here
drivers/staging/stealth/stealth_proc.c
drivers/staging/stealth/stealth_neigh.c
drivers/staging/stealth/stealth_tcp.c
drivers/staging/stealth/stealth_capture.c
drivers/staging/stealth/stealth_ids.c
drivers/staging/stealth/stealth_tunnel.c
Six proc file tables were declared as struct proc_ops, an API this tree's
include/linux/proc_fs.h never defines (proc_create() here still takes
const struct file_operations *):

../drivers/staging/stealth/stealth_proc.c:244:30: error: variable has incomplete type 'const struct proc_ops'
../drivers/staging/stealth/stealth_neigh.c:657:30: error: variable has incomplete type 'const struct proc_ops'
../drivers/staging/stealth/stealth_tcp.c:349:30: error: variable has incomplete type 'const struct proc_ops'
../drivers/staging/stealth/stealth_capture.c:184:30: error: variable has incomplete type 'const struct proc_ops'
../drivers/staging/stealth/stealth_ids.c:324:30: error: variable has incomplete type 'const struct proc_ops'

All seven tables (stealth_tunnel.c's had the same shape but hadn't been
reached by the build yet) are now struct file_operations, with each
proc_open/proc_read/proc_write/proc_lseek/proc_release/proc_poll field
renamed to its file_operations equivalent (open/read/write/llseek/release/
poll) and .owner = THIS_MODULE added.

Signed-off-by: Varakumar <varakumar7000@gmail.com>