[mm] slub: use __obj_to_index() in validate_slab()
mm/slub.c
validate_slab() called slab_index(p, s, addr) for the SLUB_RED_ACTIVE
check, but slab_index() was removed in favour of __obj_to_index(). Replaces
the call with __obj_to_index(s, addr, p).

mm/slub.c:4604:17: error: implicit declaration of function 'slab_index' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Varakumar <varakumar7000@gmail.com>