[fs] include close_range.h in file.c
fs/file.c
__close_range() uses CLOSE_RANGE_UNSHARE and CLOSE_RANGE_CLOEXEC, which are
defined in <linux/close_range.h>; the header is now included.

fs/file.c:766:16: error: use of undeclared identifier 'CLOSE_RANGE_UNSHARE'
fs/file.c:766:38: error: use of undeclared identifier 'CLOSE_RANGE_CLOEXEC'

Signed-off-by: Varakumar <varakumar7000@gmail.com>