[sysrq] add sysrq_mask()
drivers/tty/sysrq.c
include/linux/sysrq.h
Adds sysrq_mask(), which returns 1 when sysrq_always_enabled is set and
the current sysrq_enabled mask otherwise, and exports it. pwrkey-sync
calls it to save the mask before temporarily enabling all sysrq keys and
to restore it afterwards.

drivers/input/misc/pwrkey-sync.c:33:9: error: implicit declaration of function 'sysrq_mask' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Varakumar <varakumar7000@gmail.com>