[staging] stealth: include ip6_checksum.h for csum_ipv6_magic
drivers/staging/stealth/stealth_craft.c
csum_ipv6_magic() is declared in net/ip6_checksum.h, which net/ipv6.h does
not pull in:

../drivers/staging/stealth/stealth_craft.c:212:16: error: implicit declaration of function 'csum_ipv6_magic' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Varakumar <varakumar7000@gmail.com>