[net] sync the sockopt/compat series files with Sakura.MTX-23.2
net/compat.c
net/socket.c
net/ipv4/ip_sockglue.c
net/ipv6/ipv6_sockglue.c
include/net/compat.h
include/linux/socket.h
Replaces these files with the versions from Sakura.MTX-23.2. They belong to
the 5.9 sockptr_t / compat_{get,set}sockopt removal series. Replaying that
series' commits onto this tree left the files in a state that does not
build (duplicate scm_detach_fds_compat(), missing compat_group_filter and
cmsg declarations, sockptr_t vs char * mismatches).

net/compat.c:268:6: error: use of undeclared identifier 'msg'; did you mean 'kmsg'?
net/compat.c:273:6: error: redefinition of 'scm_detach_fds_compat'
net/ipv4/ip_sockglue.c:694:34: error: variable has incomplete type 'struct compat_group_source_req'

Signed-off-by: Varakumar <varakumar7000@gmail.com>
Credits: Madara273 (https://github.com/Madara273/Sakura.MTX-OP9-Pro) - these files and the upstream patch series behind them