[zram] use the 5.4 block layer API in the writeback and bio paths
drivers/block/zram/zram_drv.c
- blkdev_get_by_dev() takes (dev, FMODE_READ | FMODE_WRITE | FMODE_EXCL,
  holder) and blkdev_put() takes the same mode instead of the holder.
- bio_alloc() takes (gfp, nr_vecs) and bio_init() takes (bio, vecs, nr);
  the bdev and opf are set with bio_set_dev() and bi_opf.
- memcpy_to_bvec() and memcpy_from_bvec() are defined locally on top of
  memcpy_to_page()/memcpy_from_page().

drivers/block/zram/zram_drv.c:576:19: error: incompatible pointer to integer conversion passing 'struct zram *' to parameter of type 'fmode_t' (aka 'unsigned int')
drivers/block/zram/zram_drv.c:663:42: error: use of undeclared identifier 'BLK_OPEN_READ'
drivers/block/zram/zram_drv.c:737:33: error: too many arguments to function call, expected 2, have 4
drivers/block/zram/zram_drv.c:884:40: error: too many arguments to function call, expected 3, have 5
drivers/block/zram/zram_drv.c:1693:3: error: implicit declaration of function 'memcpy_to_bvec' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Varakumar <varakumar7000@gmail.com>