[net] keep sockaddr.sa_data as a fixed char[14]
include/linux/socket.h
struct sockaddr declared sa_data as a union with DECLARE_FLEX_ARRAY(), which
this tree does not have. It is back to "char sa_data[14]".

include/linux/socket.h:35:28: error: type specifier missing, defaults to 'int'

Signed-off-by: Varakumar <varakumar7000@gmail.com>