[sched] declare lockdep_tasklist_lock_is_held() unconditionally
include/linux/sched/task.h
lockdep_tasklist_lock_is_held() was declared only under CONFIG_PROVE_RCU.
The declaration is now unconditional, so callers inside
rcu_dereference_check() compile without CONFIG_PROVE_RCU.

kernel/exit.c:149:6: error: implicit declaration of function 'lockdep_tasklist_lock_is_held' [-Werror,-Wimplicit-function-declaration]
kernel/pid.c:377:12: error: implicit declaration of function 'lockdep_tasklist_lock_is_held' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Varakumar <varakumar7000@gmail.com>
Credits: Madara273 (https://github.com/Madara273/Sakura.MTX-OP9-Pro) - unconditional declaration in include/linux/sched/task.h